/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/ai/AIassistant`; params?: Router.UnknownInputParams; } | { pathname: `/ai/AIChatbox`; params?: Router.UnknownInputParams; } | { pathname: `/ai/FloatingAIButton`; params?: Router.UnknownInputParams; } | { pathname: `/auth/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgotpassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/main/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/main/exercises`; params?: Router.UnknownInputParams; } | { pathname: `/main/paymentScreen`; params?: Router.UnknownInputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/profile/subscription`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/ai/AIassistant`; params?: Router.UnknownOutputParams; } | { pathname: `/ai/AIChatbox`; params?: Router.UnknownOutputParams; } | { pathname: `/ai/FloatingAIButton`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/CreateAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgotpassword`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/main/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/main/exercises`; params?: Router.UnknownOutputParams; } | { pathname: `/main/paymentScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/quiz`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/subscription`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/ai/AIassistant${`?${string}` | `#${string}` | ''}` | `/ai/AIChatbox${`?${string}` | `#${string}` | ''}` | `/ai/FloatingAIButton${`?${string}` | `#${string}` | ''}` | `/auth/CreateAccount${`?${string}` | `#${string}` | ''}` | `/auth/forgotpassword${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/main/analytics${`?${string}` | `#${string}` | ''}` | `/main/exercises${`?${string}` | `#${string}` | ''}` | `/main/paymentScreen${`?${string}` | `#${string}` | ''}` | `/profile/profile${`?${string}` | `#${string}` | ''}` | `/profile/quiz${`?${string}` | `#${string}` | ''}` | `/profile/subscription${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/ai/AIassistant`; params?: Router.UnknownInputParams; } | { pathname: `/ai/AIChatbox`; params?: Router.UnknownInputParams; } | { pathname: `/ai/FloatingAIButton`; params?: Router.UnknownInputParams; } | { pathname: `/auth/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgotpassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/main/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/main/exercises`; params?: Router.UnknownInputParams; } | { pathname: `/main/paymentScreen`; params?: Router.UnknownInputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/profile/subscription`; params?: Router.UnknownInputParams; };
    }
  }
}
